# Generated by Django 3.1.1 on 2020-10-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bar_code_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_code',
            name='carbo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='colestrol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='kcal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='natrium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='provision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='sat_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='sugar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bar_code',
            name='tra_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
