# Generated by Django 3.1.1 on 2020-10-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201007_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_code',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
