# Generated by Django 3.1.1 on 2020-10-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bar_code_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar_code',
            name='once',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
